<?php namespace ten31\Otms;

use System\Classes\PluginBase;

class Plugin extends PluginBase
{
    public function registerComponents()
    {
    }

    public function registerSettings()
    {
      
    }






    /*
    public function registerMailTemplates()
    {
        return ['ten31.leads::mail.message'=>"Message to send to potential leads.", ]; // TODO: Change the autogenerated stub
    }
*/

}
